import type { NotificationActorType, NotificationChannel } from "@/types/backend/onboarding";

type NotificationTemplateSeed = {
  key: string;
  name: string;
  actorType: NotificationActorType;
  eventType: string;
  channel: NotificationChannel;
  subject?: string;
  bodyTemplate: string;
  plainTextTemplate?: string;
  isActive?: boolean;
  version: string;
  locale?: string;
  description?: string;
};

function lines(...parts: string[]) {
  return parts.join("\n\n");
}

export const notificationTemplatesRegistry: NotificationTemplateSeed[] = [
  {
    key: "employee_application_received_email",
    name: "Employee application received email",
    actorType: "employee_applicant",
    eventType: "application_submitted",
    channel: "email",
    version: "1.0",
    subject: "SLYDE received your employee application",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "Thanks for applying for an internal employee role with SLYDE.",
      "Your application for {{roleInterest}} in {{departmentInterest}} has been received and is now in review.",
      "If your application moves forward, a SLYDE admin will send you an activation invite by email so you can create your password and begin employee onboarding.",
      "Support: {{supportEmail}} | {{supportPhone}}",
    ),
  },
  {
    key: "admin_employee_application_submitted_email",
    name: "Admin employee application submitted email",
    actorType: "admin_user",
    eventType: "employee_application_submitted",
    channel: "email",
    version: "1.0",
    subject: "New employee application: {{fullName}}",
    bodyTemplate: lines(
      "A new internal employee application has been submitted.",
      "Applicant: {{fullName}}",
      "Role interest: {{roleInterest}}",
      "Department: {{departmentInterest}}",
      "Location: {{location}}",
      "Review in control tower: {{reviewUrl}}",
    ),
  },
  {
    key: "employee_activation_ready_email",
    name: "Employee activation ready email",
    actorType: "employee_user",
    eventType: "activation_ready",
    channel: "email",
    version: "1.0",
    subject: "Activate your SLYDE employee account",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "Your SLYDE employee account is ready.",
      "Step 1: Create your password using this activation link:",
      "{{activationUrl}}",
      "Step 2: Sign in to the employee portal:",
      "{{loginUrl}}",
      "Step 3: Complete your employee onboarding profile:",
      "{{onboardingUrl}}",
      "Role: {{roleInterest}}",
      "Department: {{departmentInterest}}",
    ),
  },
  {
    key: "employee_activation_completed_email",
    name: "Employee activation completed email",
    actorType: "employee_user",
    eventType: "activation_completed",
    channel: "email",
    version: "1.0",
    subject: "Your SLYDE employee account is active",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "Your employee account activation is complete.",
      "You can now sign in using the email or phone number on your application and the password you just created.",
      "Sign in: {{loginUrl}}",
      "Then complete onboarding here: {{onboardingUrl}}",
    ),
  },
  {
    key: "employee_application_rejected_email",
    name: "Employee application rejected email",
    actorType: "employee_applicant",
    eventType: "rejected",
    channel: "email",
    version: "1.0",
    subject: "Update on your SLYDE employee application",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "We reviewed your employee application for {{roleInterest}}, but we are unable to move forward at this time.",
      "Reason: {{reviewReason}}",
      "If SLYDE opens a more suitable role later, our team may contact you again.",
    ),
  },
  {
    key: "slyder_application_received_whatsapp",
    name: "Slyder application received WhatsApp",
    actorType: "slyder_applicant",
    eventType: "application_submitted",
    channel: "whatsapp",
    version: "1.0",
    description: "Sent when a new Slyder application is received.",
    bodyTemplate: lines(
      "Hi {{firstName}}, SLYDE has received your application ({{applicationCode}}).",
      "We are building the network region by region across Jamaica, and your application is now in structured review for {{zoneName}}.",
      "You will receive updates by WhatsApp and email if we need more information or when your application moves forward.",
      "Support: {{supportContact}}",
    ),
  },
  {
    key: "slyder_application_received_email",
    name: "Slyder application received email",
    actorType: "slyder_applicant",
    eventType: "application_submitted",
    channel: "email",
    version: "1.0",
    subject: "SLYDE application received: {{applicationCode}}",
    description: "Email confirmation after public Slyder application submission.",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "Thanks for applying to become a Slyder. We have received your application for {{zoneName}} and assigned reference {{applicationCode}}.",
      "SLYDE is launching region by region across Jamaica. Your application will be reviewed alongside document completeness, area readiness, and operational requirements.",
      "What happens next:",
      "- You will receive WhatsApp and email confirmation that your submission is in review.",
      "- The SLYDE team may contact you if we need more information or documents.",
      "- If approved, you will receive activation guidance for the SLYDE app and setup steps.",
      "Support: {{supportEmail}} | {{supportPhone}}",
    ),
  },
  {
    key: "slyder_documents_requested_whatsapp",
    name: "Slyder documents requested WhatsApp",
    actorType: "slyder_applicant",
    eventType: "docs_requested",
    channel: "whatsapp",
    version: "1.0",
    bodyTemplate: lines(
      "Hi {{firstName}}, SLYDE needs a few more items to continue reviewing your application ({{applicationCode}}).",
      "Requested items: {{requestedItems}}",
      "{{reviewReason}}",
      "Reply to the SLYDE team or watch for follow-up instructions by email.",
    ),
  },
  {
    key: "slyder_documents_requested_email",
    name: "Slyder documents requested email",
    actorType: "slyder_applicant",
    eventType: "docs_requested",
    channel: "email",
    version: "1.0",
    subject: "Additional documents needed for your SLYDE application",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "We need additional information to continue reviewing your SLYDE application ({{applicationCode}}).",
      "Requested items: {{requestedItems}}",
      "Review note: {{reviewReason}}",
      "Once these items are received, your application can move forward in review.",
    ),
  },
  {
    key: "slyder_documents_review_complete_whatsapp",
    name: "Slyder documents review complete WhatsApp",
    actorType: "slyder_user",
    eventType: "documents_review_complete",
    channel: "whatsapp",
    version: "1.0",
    bodyTemplate: lines(
      "Hi {{firstName}}, SLYDE has completed review of your required documents.",
      "{{nextStepBody}}",
      "Continue here: {{onboardingUrl}}",
    ),
  },
  {
    key: "slyder_documents_review_complete_email",
    name: "Slyder documents review complete email",
    actorType: "slyder_user",
    eventType: "documents_review_complete",
    channel: "email",
    version: "1.0",
    subject: "Your SLYDE document review is complete",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "SLYDE has completed review of your required onboarding documents for {{zoneName}}.",
      "{{nextStepTitle}}",
      "{{nextStepBody}}",
      "Continue here:",
      "{{onboardingUrl}}",
    ),
  },
  {
    key: "slyder_status_update_whatsapp",
    name: "Slyder status update WhatsApp",
    actorType: "slyder_user",
    eventType: "status_update",
    channel: "whatsapp",
    version: "1.0",
    bodyTemplate: lines(
      "Hi {{firstName}}, here is your latest SLYDE onboarding update.",
      "{{statusTitle}}",
      "{{statusBody}}",
      "Continue here: {{onboardingUrl}}",
    ),
  },
  {
    key: "slyder_status_update_email",
    name: "Slyder status update email",
    actorType: "slyder_user",
    eventType: "status_update",
    channel: "email",
    version: "1.0",
    subject: "Your latest SLYDE onboarding update",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "{{statusTitle}}",
      "{{statusBody}}",
      "Continue here:",
      "{{onboardingUrl}}",
    ),
  },
  {
    key: "slyder_approved_whatsapp",
    name: "Slyder approved WhatsApp",
    actorType: "slyder_applicant",
    eventType: "approved",
    channel: "whatsapp",
    version: "1.0",
    bodyTemplate: lines(
      "Hi {{firstName}}, your SLYDE application ({{applicationCode}}) has been approved.",
      "Your access is being prepared for the SLYDE app. Complete activation and setup so you are positioned as {{zoneName}} approaches launch.",
      "Activation channel: {{activationChannel}}",
    ),
  },
  {
    key: "slyder_approved_email",
    name: "Slyder approved email",
    actorType: "slyder_applicant",
    eventType: "approved",
    channel: "email",
    version: "1.0",
    subject: "Your SLYDE application has been approved",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "Your SLYDE application ({{applicationCode}}) has been approved.",
      "We are now preparing your Slyder account and activation flow. You will need to complete setup, readiness requirements, and any remaining onboarding tasks before going online.",
      "This does not mean your area is live yet. It means you are positioned early as {{zoneName}} approaches launch readiness.",
    ),
  },
  {
    key: "slyder_rejected_email",
    name: "Slyder rejected email",
    actorType: "slyder_applicant",
    eventType: "rejected",
    channel: "email",
    version: "1.0",
    subject: "Update on your SLYDE application",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "We reviewed your SLYDE application ({{applicationCode}}), but we are unable to move forward at this time.",
      "Reason: {{reviewReason}}",
      "If the SLYDE team invites a future resubmission or requests updated information, we will contact you directly.",
    ),
  },
  {
    key: "slyder_activation_ready_whatsapp",
    name: "Slyder activation ready WhatsApp",
    actorType: "slyder_user",
    eventType: "activation_ready",
    channel: "whatsapp",
    version: "1.0",
    bodyTemplate: lines(
      "Your SLYDE account is ready for activation.",
      "Open this activation link to set your password: {{activationUrl}}",
      "After setting your password, sign in here: {{loginUrl}}",
      "Then complete legal, setup, and readiness so you are positioned for launch in {{zoneName}}.",
    ),
  },
  {
    key: "slyder_activation_ready_email",
    name: "Slyder activation ready email",
    actorType: "slyder_user",
    eventType: "activation_ready",
    channel: "email",
    version: "1.0",
    subject: "Activate your SLYDE account",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "Your SLYDE account is ready for activation.",
      "Step 1: Open your activation link and set your password:",
      "{{activationUrl}}",
      "Step 2: Sign in to your Slyder account:",
      "{{loginUrl}}",
      "Step 3: Complete the final legal, setup, and readiness steps:",
      "{{onboardingUrl}}",
      "You must finish activation and onboarding before you can become eligible for live delivery work in {{zoneName}}.",
    ),
  },
  {
    key: "slyder_activation_completed_email",
    name: "Slyder activation completed email",
    actorType: "slyder_user",
    eventType: "activation_completed",
    channel: "email",
    version: "1.0",
    subject: "Your SLYDE activation is complete",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "Your SLYDE account activation is now complete.",
      "You can now sign in with the same approved email or phone number and the password you just created.",
      "Next steps:",
      "1. Sign in to your Slyder account: {{loginUrl}}",
      "2. Complete your remaining onboarding steps: {{onboardingUrl}}",
      "3. Watch for updates from SLYDE about document review, onboarding readiness, and zone launch for {{zoneName}}.",
    ),
  },
  {
    key: "slyder_login_otp_sms",
    name: "Slyder login OTP SMS",
    actorType: "slyder_user",
    eventType: "login_otp",
    channel: "sms",
    version: "1.0",
    bodyTemplate: lines(
      "Your SLYDE login code is {{otpCode}}.",
      "This code will expire shortly. Do not share it with anyone.",
    ),
  },
  {
    key: "slyder_login_otp_email",
    name: "Slyder login OTP email",
    actorType: "slyder_user",
    eventType: "login_otp",
    channel: "email",
    version: "1.0",
    subject: "Your SLYDE login code",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "Your SLYDE one-time login code is {{otpCode}}.",
      "This code will expire shortly. Do not share it with anyone.",
    ),
  },
  {
    key: "slyder_zone_live_whatsapp",
    name: "Slyder zone live WhatsApp",
    actorType: "slyder_user",
    eventType: "zone_live",
    channel: "whatsapp",
    version: "1.0",
    bodyTemplate: lines(
      "{{zoneName}} is now live on SLYDE.",
      "If your setup is complete and you are eligible, you can begin receiving delivery opportunities through the SLYDE network.",
      "If you are not yet ready, complete your setup now.",
    ),
  },
  {
    key: "slyder_zone_live_email",
    name: "Slyder zone live email",
    actorType: "slyder_user",
    eventType: "zone_live",
    channel: "email",
    version: "1.0",
    subject: "{{zoneName}} is now live on SLYDE",
    bodyTemplate: lines(
      "Hi {{fullName}},",
      "{{zoneName}} is now live on the SLYDE network.",
      "Eligible Slyders in your zone can now begin receiving delivery opportunities. If you still have setup steps pending, complete them as soon as possible to become operationally ready.",
    ),
  },
  {
    key: "merchant_interest_received_email",
    name: "Merchant interest received email",
    actorType: "merchant_interest",
    eventType: "interest_submitted",
    channel: "email",
    version: "1.0",
    subject: "SLYDE received your business inquiry",
    bodyTemplate: lines(
      "Hi {{contactName}},",
      "Thanks for your interest in SLYDE. We have received your business inquiry for {{zoneName}}.",
      "SLYDE is onboarding merchants region by region based on launch readiness, courier coverage, and operational fit.",
      "A member of the SLYDE team may contact you regarding onboarding, waitlist status, and service availability in your area.",
    ),
  },
  {
    key: "merchant_interest_received_whatsapp",
    name: "Merchant interest received WhatsApp",
    actorType: "merchant_interest",
    eventType: "interest_submitted",
    channel: "whatsapp",
    version: "1.0",
    bodyTemplate: lines(
      "SLYDE has received your business inquiry for {{businessName}} in {{zoneName}}.",
      "We are onboarding merchants region by region and will contact you as your area approaches service readiness.",
    ),
  },
  {
    key: "merchant_waitlist_confirmation_email",
    name: "Merchant waitlist confirmation email",
    actorType: "merchant_interest",
    eventType: "waitlist_confirmation",
    channel: "email",
    version: "1.0",
    subject: "{{businessName}} has been added to the SLYDE waitlist",
    bodyTemplate: lines(
      "Hi {{contactName}},",
      "{{businessName}} is now on the SLYDE merchant waitlist for {{zoneName}}.",
      "This does not guarantee immediate activation. We use courier readiness and launch control to determine when a zone is ready for merchant onboarding.",
    ),
  },
  {
    key: "merchant_prelaunch_ready_email",
    name: "Merchant prelaunch ready email",
    actorType: "merchant_interest",
    eventType: "prelaunch_ready",
    channel: "email",
    version: "1.0",
    subject: "{{zoneName}} is nearing merchant onboarding readiness",
    bodyTemplate: lines(
      "Hi {{contactName}},",
      "{{zoneName}} is nearing launch readiness on SLYDE.",
      "Your business is well positioned for the next stage of merchant onboarding. The SLYDE team may reach out for follow-up information before activation.",
    ),
  },
  {
    key: "merchant_zone_live_email",
    name: "Merchant zone live email",
    actorType: "merchant_interest",
    eventType: "zone_live",
    channel: "email",
    version: "1.0",
    subject: "{{zoneName}} is now live on SLYDE",
    bodyTemplate: lines(
      "Hi {{contactName}},",
      "{{zoneName}} is now live on the SLYDE network.",
      "If your business is approved and operationally ready, the SLYDE team will guide you through the next onboarding step.",
    ),
  },
  {
    key: "merchant_onboarding_invite_email",
    name: "Merchant onboarding invite email",
    actorType: "merchant_interest",
    eventType: "onboarding_invite",
    channel: "email",
    version: "1.0",
    subject: "You are invited to begin merchant onboarding with SLYDE",
    bodyTemplate: lines(
      "Hi {{contactName}},",
      "SLYDE is ready to begin the next onboarding step for {{businessName}}.",
      "We will guide you through the required onboarding, legal, and operational setup needed before activation.",
    ),
  },
  {
    key: "admin_zone_near_ready_alert",
    name: "Admin zone near ready alert",
    actorType: "admin_user",
    eventType: "zone_near_ready",
    channel: "internal",
    version: "1.0",
    bodyTemplate: lines(
      "{{zoneName}} is nearing launch readiness.",
      "Ready Slyders: {{readyCount}} / {{requiredReadyCount}}",
      "{{remainingNeeded}} more ready Slyders needed before the zone reaches threshold.",
    ),
  },
  {
    key: "admin_zone_ready_alert",
    name: "Admin zone ready alert",
    actorType: "admin_user",
    eventType: "zone_ready",
    channel: "internal",
    version: "1.0",
    bodyTemplate: lines(
      "{{zoneName}} has reached launch readiness.",
      "Ready Slyders: {{readyCount}} / {{requiredReadyCount}}",
      "This zone is ready for launch-control review.",
    ),
  },
  {
    key: "admin_notification_failure_alert",
    name: "Admin notification failure alert",
    actorType: "admin_user",
    eventType: "notification_failed",
    channel: "internal",
    version: "1.0",
    bodyTemplate: lines(
      "A SLYDE notification failed to send.",
      "Template: {{templateKey}}",
      "Recipient: {{recipient}}",
      "Error: {{errorMessage}}",
    ),
  },
];
